export const chirps: string[] = [
  "Give your balls a tug.",
  "Settle down.",
  "Sticks are unbelievable.",
  "Fer what?",
  "Shut the fuck up, Sanguinet.",
  "You're spare parts, bud.",
  "Pitter patter, let's get at 'er.",
  "That's a ten-ply call, ref.",
  "Take a lap, you fucking pheasant.",
  "Your mom's twat's so swampy not even Ducks Unlimited'll touch her.",
  "You skate like you got two left sticks.",
  "I've seen better hands on a digital clock.",
  "Your breath could knock a buzzard off a shit wagon.",
  "You're softer than a Timmies roll-up rim.",
  "Your mitts are made of concrete, eh?",
  "Nice hands, feet. Nice feet, hands.",
  "You couldn't hit water if you fell out of a boat.",
  "Get off the ice before you hurt the ice.",
  "You're about as useful as a screen door on a submarine.",
  "Your backcheck's softer than your mom's cookies.",
  "Go take a knee, you fucking turtle.",
  "You play like your controller's unplugged.",
  "Big guy, big mouth, no shot. Ferda.",
  "Your flow's got more salad than a deli.",
  "You chirp like a peewee with a sore throat.",
  "I'd say you're a plug, but even plugs fit in.",
  "You got hands like feet and feet like hands.",
  "Take off, ya hoser.",
  "Your shot's so weak my grandma'd pad it away.",
  "You're the reason they put nets on the glass.",
  "You got a face only a mother could chirp.",
  "That release is slower than your mom's wifi.",
  "You block shots with your face 'cause your stick's useless.",
  "Here's the deal: you're not that guy, pal.",
  "You're more offside than your mom at the bingo hall.",
  "Your celly's for a goal, not a dump-in. Act like it.",
  "You couldn't dangle your way out of a wet paper bag.",
  "Your edges are duller than a sack of hammers.",
  "You chirp the ref more than you backcheck.",
  "Tape your stick, not your ankles, you fucking bender.",
  "Your coach plays you 'cause he lost a bet.",
  "You got a slapper that couldn't break a spiderweb.",
  "Skate's on the wrong foot, genius.",
  "You're a fourth-liner in a beer league. Settle down.",
  "Your mom does the dishes in her Shoresy jersey.",
  "You'd lose a fight to a wet napkin.",
  "That was softer than a pillow fight in a daycare.",
  "You're like a pylon, but with worse balance.",
  "Give the puck to someone who can read, bud.",
  "You play like you've got two left feet and no right ones.",
  "Your biscuit's always in the wrong basket.",
  "You couldn't bury a puck in a cemetery.",
  "The net's six feet wide and you still missed.",
  "You're the human version of a turnover.",
  "Your wrist shot's a danger to nobody but the glass.",
  "Ferda? More like fer-what, bud?",
  "You got hands like a goalie with no stick.",
  "Your slap shot's a fart in the wind.",
  "You chirp like your voice is still breaking.",
  "I've seen better footwork in a senior's shinny game.",
  "You're built like a brick shithouse and play like a port-a-potty.",
  "Your celly should be an apology.",
  "You couldn't hit a one-timer if the puck was stapled to your stick.",
  "That was a muffin, not a shot.",
  "You're softer than summer ice.",
  "Your helmet's the only thing holding your head together.",
  "You'd be a beauty if you weren't so fuckin' ugly, bud.",
  "Go sniff a jockstrap, you fucking animal.",
  "You're the reason the team runs bag skates.",
  "Your backhand's a cry for help.",
  "You play like you're late for a dentist appointment.",
  "Keep your head up or you'll end up in the second row, bud.",
  "Your vision's worse than a goalie without glasses.",
  "You pass like you're throwing a curling rock.",
  "You're not a hockey player, you're a hazard.",
  "Give your balls a tug and get back on the bench.",
  "You couldn't win a draw against a broken stick.",
  "Your mom's the only reason you made the team.",
  "That save was luck, and you know it, you sieve.",
  "You're a sieve with a jersey on.",
  "Your five-hole's so big I could drive a zamboni through it.",
  "You read the play like a goalie reads a menu.",
  "Your glove hand's a suggestion, not a save.",
  "You couldn't stop a beach ball with a tennis racket.",
  "Even your posts don't wanna play for you.",
  "Your rebound control's a public service announcement.",
  "You're not a goalie, you're a speed bump.",
  "Chirp all you want, you're still down by three, you fucking plug.",
  "Scoreboard, bud. Read it slowly.",
  "You can't buy a goal with your daddy's money.",
  "Your team folds faster than your mom at poker night.",
  "Sudbury's full of chirps and you're all of them.",
  "I'd chirp your sister, but she's too busy being better than you.",
  "You're softer than a bag of milk left in the sun.",
  "The only thing you can lift is the team's spirits, and barely.",
  "Your chirps are like your shots: wide and sad.",
  "Go back to house league, you fuckin' dust bunny.",
  "Sticks are unbelievable, but you're not.",
  "You're the reason the rink has a quiet room.",
  "One more shift like that and I'm calling your billet.",
];
